### ISSUE TITLE
Unable to uninstall x-pack with elasticsearch:5.2.0 image

### ISSUE THREAD

**Issue by yuemin-li** [docker-library/elasticsearch#156]
Hi, 

There is a closed issue #141 for the same observation, but it's closed without indicating how it's resolved. 
I can still reproduce the issue here. 
I'm trying to unistall the x-pack for development env, but got the following error. 
The version is `docker.elastic.co/elasticsearch/elasticsearch:5.2.0`.
I'm also running a `docker.elastic.co/kibana/kibana:5.2.0` along with elasticsearch, that one seems to be fine if I wanna remove x-pack. 

```bash-4.3$ ./bin/elasticsearch-plugin remove x-pack
-> Removing x-pack...
Exception in thread "main" java.nio.file.AtomicMoveNotSupportedException: /usr/share/elasticsearch/plugins/x-pack -> /usr/share/elasticsearch/plugins/.removing-x-pack: Cross-device link
	at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:394)
	at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262)
	at java.nio.file.Files.move(Files.java:1395)
	at org.elasticsearch.plugins.RemovePluginCommand.execute(RemovePluginCommand.java:88)
	at org.elasticsearch.plugins.RemovePluginCommand.execute(RemovePluginCommand.java:59)
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.Command.main(Command.java:88)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
```

Thanks!

**Comment by yosifkit** [comment]
This repo is for the `elasticsearch` image and not the `docker.elastic.co/elasticsearch/elasticsearch` image.  This image does not have x-pack installed by default (or any other plugin): :confused:
```console
$ docker run -it --rm elasticsearch bash
root@148fc3b743ff:/usr/share/elasticsearch# elasticsearch-plugin remove x-pack
-> Removing x-pack...
ERROR: plugin x-pack not found; run 'elasticsearch-plugin list' to get list of installed plugins
root@10f45fb62164:/usr/share/elasticsearch# elasticsearch-plugin list
root@148fc3b743ff:/usr/share/elasticsearch# exit
```

**Comment by yuemin-li** [comment]
uhm, ic. sry about that.
Will close the issue here. 😔
