### ISSUE TITLE
Configuration problem

### ISSUE THREAD

**Issue by ak47wyh** [docker-library/elasticsearch#162]
spring.data.elasticsearch.cluster-name=elasticsearch
spring.data.elasticsearch.cluster-nodes=127.0.0.1:9300
In the spring boot configured as above, error NoNodeAvailableException [None of the configured nodes are available: [{# transport # -1} {127.0.0.1} {127.0.0.1:9300}，elastic is start

**Comment by ak47wyh** [comment]
@olivere please help me
spring.data.elasticsearch.cluster-name=elasticsearch
spring.data.elasticsearch.cluster-nodes=127.0.0.1:9300

$ curl -XGET http://127.0.0.1:9200/_nodes/http?pretty
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
100 486 100 486 0 0 740 0 --:--:-- --:--:-- --:--:-- 740{
"cluster_name" : "elasticsearch",
"nodes" : {
"Ua1k4rWsTNKP6M5xObho1g" : {
"name" : "Master",
"transport_address" : "127.0.0.1:9300",
"host" : "127.0.0.1",
"ip" : "127.0.0.1",
"version" : "2.3.4",
"build" : "e455fd0",
"http_address" : "127.0.0.1:9200",
"http" : {
"bound_address" : [ "127.0.0.1:9200" ],
"publish_address" : "127.0.0.1:9200",
"max_content_length_in_bytes" : 104857600
}
}
}
}
NoNodeAvailableException[None of the configured nodes are available: []
]
at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:290)
at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:207)
at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:55)
at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:288)
at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1226)
at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:86)
at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:56)
at org.elasticsearch.action.ActionRequestBuilder.get(ActionRequestBuilder.java:64)
at com.didispace.domain.esTest2.test(esTest2.java:59)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)

**Comment by ak47wyh** [comment]
The rewrite item has not changed，the project is working !

**Comment by imyoungyang** [comment]
@ak47wyh may I know how do you solve this issue?
I encountered the same error message:

Exception in thread "main" NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{pUzYhqM6TKiUL94PydViwg}{127.0.0.1}{127.0.0.1:9300}]]

My java code is followed the document: 
[](https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/transport-client.html)

`TransportClient client = new PreBuiltTransportClient(Settings.EMPTY)
                .addTransportAddress(new InetSocketTransportAddress(InetAddress.getByName("127.0.0.1"), 9300));`

Actually, the nodes status is as correct:

> {
  "_nodes": {
    "total": 1,
    "successful": 1,
    "failed": 0
  },
  "cluster_name": "elasticsearch",
  "nodes": {
    "tc29L00fSAWX4_SdbvWbSQ": {
      "name": "tc29L00",
      "transport_address": "127.0.0.1:9300",
      "host": "127.0.0.1",
      "ip": "127.0.0.1",
      "version": "5.4.3",
      "build_hash": "eed30a8",
      "total_indexing_buffer": 213005107,
      "roles": [
        "master",
        "data",
        "ingest"
      ],
      "settings": {
        "client": {
          "type": "node"
        },
        "cluster": {
          "name": "elasticsearch"
        },

**Comment by jeremieSimon** [comment]
@ak47wyh I get the same issue. How did you solve it?

**Comment by imyoungyang** [comment]
@jeremieSimon I solved this issue byself. 

1. first of all, you need to overwrite the default elasticsearch.yml file in the docker container with the following settings:
```
transport.host: 0.0.0.0
http.host: 0.0.0.0
discovery.zen.minimum_master_nodes: 1
```
The docker run command environment variable seems did not function well for ```transport.host```.

```
docker run -d --name elas elasticsearch -Etransport.host=0.0.0.0 -Ediscovery.zen.minimum_master_nodes=1
```

2. If you are only one node, you must turn off the sniff feature.
.put("client.transport.sniff", false)

**Comment by ak47wyh** [comment]
Yes, but I did not find a problem@jeremieSimon
