### ISSUE TITLE
 Unable to access 'path.scripts'

### ISSUE THREAD

**Issue by richisharma** [docker-library/elasticsearch#175]
Hi, I am getting below error in administrative command prompt while running elastic search

Exception in thread "main" java.lang.IllegalStateException: Unable to access 'path.scripts' (C:\elasticsearch-2.3.1\config\scripts)
Likely root cause: java.nio.file.NotDirectoryException: C:\elasticsearch-2.3.1\config\scripts
        at org.elasticsearch.bootstrap.Security.ensureDirectoryExists(Security.java:340)
        at org.elasticsearch.bootstrap.Security.addPath(Security.java:314)
        at org.elasticsearch.bootstrap.Security.addFilePermissions(Security.java:248)
        at org.elasticsearch.bootstrap.Security.createPermissions(Security.java:212)
        at org.elasticsearch.bootstrap.Security.configure(Security.java:118)
        at org.elasticsearch.bootstrap.Bootstrap.setupSecurity(Bootstrap.java:196)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:167)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.

Also C:\elasticsearch-2.3.1\config\scripts exist. but still I get the error

![capture](https://user-images.githubusercontent.com/36769530/36605337-462ae762-1875-11e8-8d1f-1f09def5d8ea.PNG).

Please help me resolve this issue

**Comment by tianon** [comment]
This looks like an issue with running Elasticsearch on your (Windows) host -- this is the GitHub repository for the https://hub.docker.com/_/elasticsearch/ Docker image, which does not even have a Windows variant. :sweat_smile:
