### ISSUE TITLE
Apple M1 support

### ISSUE THREAD

**Issue by joshua-barnett** [docker-library/elasticsearch#197]
Currently if you try to start the `elasticsearch:7.14.1` image on an Apple M1 system with the platform set to `linux/amd64` the container will fail to start with the following error message.

```
Exception in thread "main" java.io.IOException: Cannot run program "/usr/share/elasticsearch/jdk/bin/java": error=0, Failed to exec spawn helper: pid: 239, exit value: 1
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1142)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
        at org.elasticsearch.tools.launchers.JvmOption.flagsFinal(JvmOption.java:107)
        at org.elasticsearch.tools.launchers.JvmOption.findFinalOptions(JvmOption.java:81)
        at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:38)
        at org.elasticsearch.tools.launchers.JvmOptionsParser.jvmOptions(JvmOptionsParser.java:135)
        at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:86)
Caused by: java.io.IOException: error=0, Failed to exec spawn helper: pid: 239, exit value: 1
        at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:313)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1109)
        ... 6 more
```

Presumably this is an issue in the `amd64` emulation provided by QEMU and Java?

**Comment by tianon** [comment]
Yep, sounds like an emulation issue.  However, `elasticsearch:7.14.1` _should_ support `arm64v8` -- any particular reason you're not just using the ARM version?
