### ISSUE TITLE
Cant connect using java client (NoNodeAvailableException)

### ISSUE THREAD

**Issue by andrestc** [docker-library/elasticsearch#38]
Hi,

Im starting the image using Kitematic on Mac OS X. The cluster starts perfectly and i can view the cluster status thru the browser. But, when trying to connecting to the cluster using the java client, i have the following issue:
[info] 2015-06-20 18:05:51 WARN  ExceptionFilter:41 - exception: uri:/api/packages/locations exception: org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: []
[info] org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: []
[info] 	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:278)
[info] 	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:197)
[info] 	at org.elasticsearch.client.transport.support.InternalTransportIndicesAdminClient.execute(InternalTransportIndicesAdminClient.java:86)
[info] 	at org.elasticsearch.client.support.AbstractIndicesAdminClient.exists(AbstractIndicesAdminClient.java:163)
[info] 	at org.elasticsearch.action.admin.indices.exists.indices.IndicesExistsRequestBuilder.doExecute(IndicesExistsRequestBuilder.java:53)
[info] 	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:91)

Do i have to do any specific configuration to make the image work with the java client?

**Comment by andrestc** [comment]
I forgot to mention that im using the 1.4 version.

**Comment by andrestc** [comment]
The problem is because i had sniffing enabled on the client. I found a fix in a issue in another repo (https://github.com/olivere/elastic/issues/57#issuecomment-88697714). Maybe this information could be stated somewhere here (i havent found).

thanks.
