### ISSUE TITLE
iptables issues?

### ISSUE THREAD

**Issue by lrhazi** [docker-library/elasticsearch#46]
Hello,

Just installed this containe on 4 RedHat entr Linux 7 VMs.... with a config like so:

    cluster.name: Aves
    node.name: "aves-01"
    path.logs: /var/log/elasticsearch
    network.publish_host: 192.168.88.145
    discovery.zen.ping.multicast.enabled: false
    discovery.zen.ping.timeout: 3s
    discovery.zen.minimum_master_nodes: 3
    discovery.zen.ping.unicast.hosts: [
    "192.168.88.190:9300",
    "192.168.88.191:9300",
    "192.168.88.215:9300",
    
      ]

When I start the containers... it seems to work fine (kopf plugin shows the cluster state as being good), but, all instances constantly log network connection errors like so:

    [2015-08-22 17:44:20,006][WARN ][transport.netty          ] [aves-01] exception caught on transport layer [[id: 0xfda51f31]], closing connection
    java.net.NoRouteToHostException: No route to host
            at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
            at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
            at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152)
            at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
            at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
            at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
            at org.elasticsearch.common.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
            at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
            at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
            at java.lang.Thread.run(Thread.java:745)

and tcpdump shows constant reject like so:

    listening on any, link-type LINUX_SLL (Linux cooked), capture size 65535 bytes
    13:58:52.095383 IP 192.168.88.145 > 172.17.0.2: ICMP host 192.168.88.145 unreachable - admin prohibited, length 68
    13:58:52.095387 IP 192.168.88.145 > 172.17.0.2: ICMP host 192.168.88.145 unreachable - admin prohibited, length 68
    13:58:52.095621 IP 192.168.88.145 > 172.17.0.2: ICMP host 192.168.88.145 unreachable - admin prohibited, length 68
    13:58:52.095623 IP 192.168.88.145 > 172.17.0.2: ICMP host 192.168.88.145 unreachable - admin prohibited, length 68

As if iptables is rejecting traffic from the container to itself? 192.168.88.145 being the host IP, and 172.17.0.2 the container IP. the icmp packet details show this is for tcp port 9300.

Whats going on?

Thank you so much.

**Comment by lrhazi** [comment]
I found that adding this rule, seems to fix the issue... but I think I should not need to add it, right?
```
-A INPUT -s 172.17.0.0/16 -m comment --comment "011 allow all traffic from DOCKER subnet" -j ACCEPT
```

**Comment by ggtools** [comment]
When I look at your configuration, I found strange that you use `192.168.88.145` as `network.publish_host`. I you are using a bridge network as it seems the containers addresses will be in the `172.17.0.0/16` range. So definitely not `192.168.88.145`. IMHO you should remove this and let Elasticsearch find the publish host.

**Comment by lrhazi** [comment]
Oh! How could elasticsearch find the real host IP address? To be clear am trying to build a cluster across several hosts.

**Comment by ggtools** [comment]
According to the documentation, ES will use the address of the first non-local-loop interface. As this address is allocated dynamically by the Docker daemon there's no way for you to put it in the configuration file.

Thinking about it your configuration could work but you'll have to bind each containers' port to a host port using -p xxxx:yyyy.  That means you'll need to use a different port for each container.

**Comment by md5** [comment]
@ggtools I was assuming based on the fact @lrhazi's config had three distinct IP addresses that there the containers being clustered are not on the same host.

@lrhazi Could you describe your setup a bit more for the sake of clarity?

**Comment by md5** [comment]
Also, I don't really see what the point would be of clustering three containers on the same host.

**Comment by ggtools** [comment]
@md5 for a production setup, no but for test purposes that would make sense. But yes a comprehensive description of the setup would be appreciated

**Comment by lrhazi** [comment]
My setup seems to work OK. One container per host, four hosts total (and dont see issues increasing that number). The containers are all started with the same command:

```
ROOT_DIR=/data/elasticsearch
docker run -d --name elasticsearch -p 9200:9200 -p 9300:9300 --restart=always -v /etc/localtime:/etc/localtime:ro -v $ROOT_DIR/config:/usr/share/elasticsearch/config -v $ROOT_DIR/data:/usr/share/elasticsearch/data docker.uis.georgetown.edu:5000/elasticsearch
```


What I dont understand is what is the traffic that was being dropped by iptables, and that was causing the above continuous errors in the log.

**Comment by ggtools** [comment]
I guess the issue here is that Elasticsearch seems to be sending `icmp` packets but if you look at the iptables rules set up by Docker you'll find only the `tcp` protocol. I don't know if there is a way to have Docker do this but in your setup it can make sense to set up the containers in host mode instead of bridge

**Comment by lrhazi** [comment]
Would definitely be great to get to the bottom of it... I'll the bridge mode, because it tells me I could, if i wanted, start more containers in on the same host, along with more containers on other hosts...

The ICMP is from iptables, saying TCP packet, addressed to port 9300, are being rejected. Like bellow.

The question is why is the ES container, with real container IP, trying to talk to itself, on the "public" or "host" IP.

```
Internet Control Message Protocol
    Type: 3 (Destination unreachable)
    Code: 10 (Host administratively prohibited)
    Checksum: 0xad10 [correct]
    Internet Protocol Version 4, Src: 172.17.0.7 (172.17.0.7), Dst: 192.168.88.145 (192.168.88.145)
        Version: 4
        Header Length: 20 bytes
        Differentiated Services Field: 0x00 (DSCP 0x00: Default; ECN: 0x00: Not-ECT (Not ECN-Capable Transport))
            0000 00.. = Differentiated Services Codepoint: Default (0x00)
            .... ..00 = Explicit Congestion Notification: Not-ECT (Not ECN-Capable Transport) (0x00)
        Total Length: 60
        Identification: 0x3bf1 (15345)
        Flags: 0x02 (Don't Fragment)
            0... .... = Reserved bit: Not set
            .1.. .... = Don't fragment: Set
            ..0. .... = More fragments: Not set
        Fragment offset: 0
        Time to live: 64
        Protocol: TCP (6)
        Header checksum: 0x6c80 [validation disabled]
            [Good: False]
            [Bad: False]
        Source: 172.17.0.7 (172.17.0.7)
        Destination: 192.168.88.145 (192.168.88.145)
        [Source GeoIP: Unknown]
        [Destination GeoIP: Unknown]
    Transmission Control Protocol, Src Port: 40500 (40500), Dst Port: 9300 (9300), Seq: 1055968273
        Source Port: 40500 (40500)
        Destination Port: 9300 (9300)
        Sequence number: 1055968273
        [Stream index: 313]
        Sequence number: 1055968273    (relative sequence number)
        Acknowledgment number: 0
        Header Length: 40 bytes
        .... 0000 0000 0010 = Flags: 0x002 (SYN)
            000. .... .... = Reserved: Not set
            ...0 .... .... = Nonce: Not set
            .... 0... .... = Congestion Window Reduced (CWR): Not set
            .... .0.. .... = ECN-Echo: Not set
            .... ..0. .... = Urgent: Not set
            .... ...0 .... = Acknowledgment: Not set
            .... .... 0... = Push: Not set
            .... .... .0.. = Reset: Not set
            .... .... ..1. = Syn: Set
                [Expert Info (Chat/Sequence): Connection establish request (SYN): server port 9300]
                    [Connection establish request (SYN): server port 9300]
                    [Severity level: Chat]
                    [Group: Sequence]
            .... .... ...0 = Fin: Not set
        Window size value: 14600
        [Calculated window size: 14600]
        Checksum: 0x9279 [validation disabled]
            [Good Checksum: False]
            [Bad Checksum: False]
        Urgent pointer: 0

```

**Comment by md5** [comment]
I tried to find the source code for `org.elasticsearch.common.netty.util.internal.DeadLockProofWorker` and it seems to be nowhere to be found... Netty itself has a similarly named class, but it only exists in the 3.X branches (cf. https://github.com/netty/netty/blob/3.10/src/main/java/org/jboss/netty/util/internal/DeadLockProofWorker.java).

@lrhazi I noticed that you're using `docker.uis.georgetown.edu:5000/elasticsearch`, so could you provide more information about which exact version of ES you're using and how it was built?

**Comment by md5** [comment]
I just cloned https://github.com/elastic/elasticsearch and ran `git log -SDeadLockProofWorker --all` and couldn't find any sign of that class.

**Comment by lrhazi** [comment]
@md5 I literally just did this:

docker pull elasticsearch
docker tag elasticsearch docker.uis.georgetown.edu:5000/elasticsearch
docker push elasticsearch docker.uis.georgetown.edu:5000/elasticsearch

No customization at all.

**Comment by lrhazi** [comment]
docker images shows this:

```
    REPOSITORY                                     TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
    docker.uis.georgetown.edu:5000/elasticsearch   latest              44d3379bfaa3        6 days ago          516 MB
    docker.io/elasticsearch                        latest              44d3379bfaa3        6 days ago          516 MB
```

**Comment by md5** [comment]
It appears that ES relocates the Netty classes here: https://github.com/elastic/elasticsearch/blob/master/distribution/shaded/pom.xml#L129-L132

**Comment by md5** [comment]
I went way too far down the rabbit hole on this one...

First, here's a `docker-compose.yml` I used to create a test cluster from four containers under my `docker-machine` dev box: https://gist.github.com/md5/8ff81304cacc3e837eab

I had to hard code the IP address of my VM in there, so that's where the "192.168.99.100" is coming from.

I then used the newly-created [`appropriate/tcpdump`](https://github.com/appropriate/docker-tcpdump) image to watch traffic on the `docker0` bridge like so:

```console
$ docker run --rm -it --net=host appropriate/tcpdump -i docker0
```

The first IP packets I saw come across the bridge were indeed coming from each container's IP address to its own published port on the host IP. In the case of the `boot2docker` ISO used by `docker-machine`, this worked fine since there are no additional `iptables` restrictions to block the packets.

I tried looking around the ElasticSearch source code to see why it's trying to connect to itself, but I couldn't figure that out. I suspect the ES developers could answer that easily enough. I believe it may be related to this code: https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/transport/netty/NettyTransport.java#L869

As for whether or not this should Just Work™, I think that stricter IPTables defaults on RedHat may be a known issue. It may be worth bringing this up through dedicated RedHat support channels, especially since you seem to have a RHEL subscription for your site.

**Comment by ggtools** [comment]
@lrhazi the network mode is set on a container basis so having a container running in host mode does not prevent you from having other containers running in bridge mode. IMHO I think it might make sense to have you ES containers running in host mode as the connections will only be performed on the host addresses (192.168.*) rather than the bridge addresses (172.17.*).

But you're right this is only a workaround and it should be great to get to the bottom of this

**Comment by lrhazi** [comment]
Thank you so much guys. and thanks @md5 for digging in the source and confirming what I am seeing.
I will see if I can get some info for ES forum about this. otherwise, let's just say that that traffic is necessary and iptables needs to be configured to allow it. This could also be unique to me.. maybe I did something funny to the iptables in my VMs... (I disabled firewalld for example, to use plain iptables).

**Comment by md5** [comment]
@ggtools In general I'm very hesitant to recommend `--net=host` since it can open up some weird scenarios, but I hear what you're saying about avoiding all the contortions necessary to get this working in bridged mode. Another possibility besides `--net=host` if performance is an issue would be to use `macvlan`. I've also seen mentions of something called `ipvlan` (see [this blog post](http://forums.rancher.com/t/how-to-launch-with-custom-network-configuration/83/12) from Rancher, including the comments).
