### ISSUE TITLE
Problems with 9300 transport port out of host

### ISSUE THREAD

**Issue by cqteixeira** [docker-library/elasticsearch#97]
Hello,

I build a elasticsearch 4 node cluster but I can't return data from ES using the container IP using transport por (9300).

I made a java client to test connection: those are the outputs from host using localhost, from host using containers ips, from another server trying to reach host:

**HOST using localhost:**

```
java -jar es-client.jar localhost 9300 staging
JarClassLoader: Warning: Null manifest from input stream associated with: lib/elasticsearch-1.7.0.jar
abr 13, 2016 5:43:18 PM org.elasticsearch.plugins.PluginsService <init>
INFORMAÇÕES: [Zartra] loaded [], sites []
nos encontrados : [[node3][KEzEzcw3SVGRSbjhnlEPeg][6ef0289a9f37][inet[/173.28.5.1:9300]]{master=true}, [node1][G43GLl_yRmmi8CS3MiCYYQ][123430ca423a][inet[/173.28.5.2:9300]]{master=true}, [node4][yIBYIH2MQTSzQiWeDYfMBw][016e42abbea0][inet[/173.28.5.3:9300]]{master=true}, [node2][yP9T0JCXTCeMZANsK-JMww][ea0ca293f9c6][inet[/173.28.5.0:9300]]{master=true}]

```
**HOST using containers ip**

```
java -jar es-client.jar 172.28.5.0 9300 staging
JarClassLoader: Warning: Null manifest from input stream associated with: lib/elasticsearch-1.7.0.jar
abr 13, 2016 5:44:03 PM org.elasticsearch.plugins.PluginsService <init>
INFORMAÇÕES: [Shatterstar] loaded [], sites []
none of nodes found
```
**Other server trying to reach containers ip**

```
java -jar es-client.jar 172.28.5.0 9300 staging
JarClassLoader: Warning: Null manifest from input stream associated with: lib/elasticsearch-1.7.0.jar
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/obvio/reclameaqui/raichu/es/probe/ProbeEsClient : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at com.simontuffs.onejar.JarClassLoader.defineClass(JarClassLoader.java:803)
	at com.simontuffs.onejar.JarClassLoader.findClass(JarClassLoader.java:710)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at com.simontuffs.onejar.JarClassLoader.loadClass(JarClassLoader.java:630)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at com.simontuffs.onejar.Boot.run(Boot.java:334)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)
```

The point is: The problem only ocurs with transport port, if I try to make queries from 9200 it works fine. 

If you need more information let me know.

**Comment by cqteixeira** [comment]
**SOLVED**

I copied ES config to docker from my ES on AWS. On my config there is no network_host set, but worked properly. I read the documentation and saw that the default value is _site_ what allows just loopback to reach it. I don't understand why my cluster works on AWS without setting this resource to _global_ or _site_.

My new config is as follows and now works properly.
`network_host: _global_`
